name: Deploy to Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - run: npm test

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: "my-filereader-${{github.sha}}"
        path: ./dist

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-filereader .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-filereader
